-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 07:21:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agendamento_consultas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agendamento_consultas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendamento_consultas` ;
USE `agendamento_consultas` ;

-- -----------------------------------------------------
-- Table `agendamento_consultas`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendamento_consultas`.`Pacientes` (
  `paciente_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`paciente_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `agendamento_consultas`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendamento_consultas`.`Consultas` (
  `consulta_id` INT NOT NULL AUTO_INCREMENT,
  `paciente_paciente_id` INT NOT NULL,
  `data_hora` DATETIME NOT NULL DEFAULT NOW(),
  `especialidade` TEXT NOT NULL,
  `obervacoes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`consulta_id`, `paciente_paciente_id`),
  INDEX `fk_consultas_paciente_idx` (`paciente_paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_paciente`
    FOREIGN KEY (`paciente_paciente_id`)
    REFERENCES `agendamento_consultas`.`Pacientes` (`paciente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
